<?php
/**
 * @date: 29.12.17 - 11:42
 */

namespace App\Modules\Integration\Modules\CoinMarketCap\Models;

use Minexsystems\Satoshi\Behaviors\SatoshiBehavior;
use Minexsystems\Satoshi\Validators\SatoshiValidator;
use App\Modules\Integration\Modules\CoinMarketCap\Models\Query\IntegrationCmcStatAggr30Query;



/**
 * @property \App\Components\Satoshi\Satoshi $priceUsd
 * @property \App\Components\Satoshi\Satoshi $priceBtc
 * @property \DateTime $createdAt
 */
class IntegrationCmcStatAggr30 extends \App\Modules\Database\IntegrationCmcStatAggr30
{
    
    public function behaviors(): array
    {
        return [
            [
                'class' => SatoshiBehavior::class,
                'fields' => [
                    'priceUsd', 'priceBtc', 'priceEth'
                ]
            ]
        ];
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [
                [
                    'priceUsd',
                    'priceBtc',
                    'priceEth',
                    'createdAt'
                ],
                'required'
            ],
            [
                [
                    'priceUsd',
                    'priceBtc',
                    'priceEth',
                ],
                SatoshiValidator::class
            ],
            [
                ['createdAt'], 'datetime'
            ],
        ];
    }
    
    /**
     * @return bool
     * @throws \yii\base\InvalidConfigException
     */
    public function beforeValidate()
    {
        $this->createdAt = \Yii::$app->formatter->asDatetime($this->createdAt);
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
    
    
    /**
     * @return IntegrationCmcStatAggr30Query
     */
    public static function find(): IntegrationCmcStatAggr30Query
    {
        return new IntegrationCmcStatAggr30Query(get_called_class());
    }
    
}